export const CHANGE_QUERY_TYPE_VAL = "CHANGE_QUERY_TYPE_VAL";

export const ADD_FILTER_ITEM = "ADD_FILTER_ITEM";
export const DELETE_FILTER_ITEM = "DELETE_FILTER_ITEM";

export const CHANGE_FILTER_VALUES = "CHANGE_FILTER_VALUES";
